### ISSUE TITLE
send() should return a Promise

### ISSUE THREAD

**Issue by ibc** [notifme/notifme-sdk#1]
callbacks and errbacks are not nice, they happen out of context making it difficult to react differently on each send request.

IMHO rather than a global callback/errback, the send() method should return a Promise that resolves with the result of rejects with an Error (or custom Error child depending the failure).

**Comment by BDav24** [comment]
Yes, `send` does return a promise with the result if you don't use a queue system.

**Comment by ibc** [comment]
Oh cool. May be the documentation/README should say that?

**Comment by BDav24** [comment]
Yes sure, I'm updating the doc right now ;)
Thanks for the feedback.

**Comment by ibc** [comment]
Thanks.

**Comment by BDav24** [comment]
https://github.com/notifme/notifme-sdk/commit/dacdd4b19dbebfb2d8e55c44cfa04c3f85fedfdf
