### ISSUE TITLE
Use broidHQ for bots notifications

### ISSUE THREAD

**Issue by nums** [notifme/notifme-sdk#15]
Thanks for your great sdk.

Just an idea :
BroidHQ (https://github.com/broidHQ/integrations) is powerful SDK to manage conversions with messaging platforms like slack etc, why not use this lib for : "Add other types of notifications based on what people ask"

**Comment by BDav24** [comment]
Hi @nums, thanks for the tip, the broidHQ lib(s) seems very nice!

I did see a similar project: https://github.com/RecastAI/bot-connector, and had the same idea. I'm working on other features at the moment. Would you be motivated to integrate a new channel? :)

**Comment by nums** [comment]
Hi @BDav24, I didn't know RecastAI and it seems good too.

We are currently working on the migration of our internal notification system to notifme. I think our first contribution will be the ovh sms provider. After that, maybe we will see for the bots ;)

**Comment by BDav24** [comment]
@nums I just published a lib to help with template definition, if you're interested: https://github.com/notifme/notifme-template
