### ISSUE TITLE
api to add new vendor

### ISSUE THREAD

**Issue by HarshaHegde1994** [notifme/notifme-sdk#17]
Hi, please give us an API to add new vendors for SMS and mail integration.

**Comment by jnoleau** [comment]
Hi,

You can add custom provider if you want, you just have to implement the `send` function which returns a Promise<id>. See `Custom` in the documentation

example with email : 

```javascript
new NotifmeSdk({
  channels: {
    email: {
      providers: [{
        type: 'custom',
        id: 'my-custom-email-provider...',
        send: async (request) => {
          // Send email
          return 'id...'
        }
      }]
    }
  }
})
```

**Comment by BDav24** [comment]
@HarshaHegde1994 I hope this answered your question. You can reopen this issue if you want more precisions.

**Comment by HarshaHegde1994** [comment]
Thanks for the reply. can you be more specific for the request and what should that function hold?

**Comment by BDav24** [comment]
`request` is one of the following types: https://github.com/notifme/notifme-sdk/blob/master/src/models/notification-request.js

And `send` should call your provider API: something like https://github.com/notifme/notifme-sdk/blob/master/src/providers/sms/46elks.js#L21-L42

What provider(s) do you want to use?

**Comment by HarshaHegde1994** [comment]
Thanks for the help @BDav24. I'm using a local service provider for sending SMS.
