### ISSUE TITLE
Add support for mailgun email provider.

### ISSUE THREAD

**Issue by HarshaHegde1994** [notifme/notifme-sdk#18]
Please add support for https://www.mailgun.com/ email provider

**Comment by BDav24** [comment]
Note: you can also use Mailgun's SMTP as a workaround for the time being.

**Comment by HarshaHegde1994** [comment]
any updates on this?

**Comment by BDav24** [comment]
I will try to add mailgun support mid-September (I'm currently in vacation). The workaround is not enough for your use case?

**Comment by HarshaHegde1994** [comment]
Yeah, it is working. however ill wait for the Mailgun support. Thank you.

**Comment by BDav24** [comment]
There you go, tell me if you find any problem.

**Comment by HarshaHegde1994** [comment]
Thank you for the support. It's very much helpful. This abstracts my code a lot.
Thank you so much.
