### ISSUE TITLE
Vote for Microsoft Teams Push Connector

### ISSUE THREAD

**Issue by recursionbane** [notifme/notifme-sdk#2]
This library looks promising! This is a vote for a [Microsoft Teams push connector](https://msdn.microsoft.com/en-us/microsoft-teams/connectors).

**Comment by BDav24** [comment]
Thanks for your vote! "Microsoft Teams Push Connector" is now on the list.

For next people wanting to vote, just add a +1 reaction to the first post.
If anyone is willing to do it, feel free to make a pull request ;)
