### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by terebentina** [notifme/notifme-sdk#23]
Hi, Could we get slack notifs as well?
I suppose we could do it with a custom webpush provider atm, right?

**Comment by BDav24** [comment]
Hi @terebentina, yes it would be a great addition to this lib. I don't know when I'll be able to integrate and test that, so if you (or someone else) is interested in adding the feature, that would be awesome.

**Comment by TheConnMan** [comment]
Slack feels like it wouldn't fit into one of the existing categories. Maybe a new "Messaging" category for Slack, HipChat, Stride, etc?

I can take a crack at hooking up the Slack REST API. Basic messages are very easy, more complicated attachments and formatting can be an additional improvement.

**Comment by BDav24** [comment]
Hi @TheConnMan yes, a new channel is definitely needed. I'd even use a new channel for each platform because I'm not really sure we'll be able to synthesize them all in one model.

And yes, basic messages are a very good starting point! When do you think you'll be able to take a crack at that?

**Comment by TheConnMan** [comment]
Depends how much down time I get on vacation this weekend. If I can get the dev environment up pretty quickly then maybe an initial PR by the end of the weekend.

**Comment by TheConnMan** [comment]
Adding bot names, channel overrides, and other incoming webhook features should be very easy now if someone else would like to try their hand at it. It is Hacktoberfest after all.
