### ISSUE TITLE
Vote for SparkPost Email API

### ISSUE THREAD

**Issue by aydrian** [notifme/notifme-sdk#3]
If you provide some guidance, I'd be happy to create a PR to implement this.

There is a [SparkPost transport](https://github.com/SparkPost/nodemailer-sparkpost-transport) for nodemailer if that makes it easier.

**Comment by BDav24** [comment]
Yes sure, I think the best way is to call SparkPost api without using the nodemailer transport.

You can check Nexmo provider, which also calls an api: https://github.com/notifme/notifme-sdk/search?utf8=%E2%9C%93&q=nexmo&type=

Let me know if you need more information.

**Comment by BDav24** [comment]
@aydrian SparkPost API is integrated :)

Note: 5 emails by day in sandbox mode to test is a bit short...

**Comment by aydrian** [comment]
Thank you. Yes. It's short by design. The deliverability of those emails are not great and were being abused by spammers. Once you create a sending domain, you can send 15K per month.

**Comment by BDav24** [comment]
@aydrian I'm unsure about `cc` and `bcc` in your code, it's not passed the same way in the documentation (https://www.sparkpost.com/docs/faq/cc-bcc-with-rest-api/), can you confirm that it's working this way?
https://github.com/notifme/notifme-sdk/blob/master/src/providers/email/sparkpost.js#L44-L45

**Comment by aydrian** [comment]
The node library has sugar methods to make passing cc & bcc easier. Let me double check.

**Comment by aydrian** [comment]
Sorry. I'll do a PR to fix those. I need to pass them in an array.

**Comment by BDav24** [comment]
It's my mistake in fact, I didn't see that the lib was transforming these fields.
I'm changing their type to make things clearer:

```
export type EmailRequestType = CommonRequestType & {
  ...
  cc?: string[],
  bcc?: string[],
  ...
}
```

**Comment by BDav24** [comment]
I can handle the change, it doesn't seem to be a big change. One question though: if I have multiple `cc`, is that the right syntax?

```
  "content": {
    "from": "you@fromyou.com",
    "headers": {
      "CC": "cc1@thatperson.com, cc2@thatperson.com, cc3@thatperson.com"
    },
    "subject": "To and CC",
    "text": "This mail was sent to to@thisperson.com while CCing cc@thatperson.com."
  }
```

**Comment by aydrian** [comment]
Here's an [example](https://github.com/SparkPost/node-sparkpost/blob/master/examples/transmissions/send_with_cc_sugar.js) with the sugar. I would just use that, then it's just an array of objects and the lib will transform it for you.
The header is only part of it. You also need them in the recipients with the `header_to` property set. Here's an [example](https://github.com/SparkPost/node-sparkpost/blob/master/examples/transmissions/send_with_cc.js).

**Comment by BDav24** [comment]
I removed the lib dependency, that's why I need to rewrite "the sugar". So:
- for `cc` and `bcc`: for each email I add an object in `recipients` containing `address.email` (original recipient) and `address.header_to` (`cc` or `bcc` address)
- for `cc` only, I add `content.headers.CC` (comma separated values)

Is this right?

**Comment by aydrian** [comment]
Yes. The lib is a thin wrapper so the structure would be the same as the second example.

**Comment by BDav24** [comment]
> verifying your domain: Status Blocked

:/

**Comment by aydrian** [comment]
Awe... It looks like your domain is already in use in another account. Do you have multiple SparkPost accounts?

**Comment by BDav24** [comment]
It seems that @jnoleau added the domain on his test account, it should be alright now. Should I contact support or you can take care of it?

**Comment by aydrian** [comment]
If he removed it from his account, I would inform support.
