### ISSUE TITLE
Support of http proxy in option

### ISSUE THREAD

**Issue by KeanuPang** [notifme/notifme-sdk#33]
In [node-fetch](https://github.com/bitinn/node-fetch), we can pass a `http.Agent` with custom proxy settings in options with [node-https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent).

So maybe we can set http/https proxy settings in option from NotifmeSdk or read from environment variables like http_proxy and https_proxy, then all providers just read this option and pass it to `node-fetch`.

ref:
[https://github.com/bitinn/node-fetch/issues/79](https://github.com/bitinn/node-fetch/issues/79)
[https://github.com/bitinn/node-fetch/issues/195](https://github.com/bitinn/node-fetch/issues/195)

**Comment by BDav24** [comment]
Ok, I'll look into it.

**Comment by BDav24** [comment]
@KeanuPang You can now pass a `NOTIFME_HTTP_PROXY` env variable. If it's set, it'll create a [node-https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent).

https://github.com/notifme/notifme-sdk/pull/34
https://github.com/notifme/notifme-sdk/releases/tag/v1.6.0

**Comment by KeanuPang** [comment]
It's great works, I love this library notifme. Thank you.

**Comment by BDav24** [comment]
@KeanuPang 
Thanks, I'm glad to hear that.
If I may ask, could you tell me how you use this lib? (context, providers...) It's useful to know in order to improve it ;)
