### ISSUE TITLE
Remove Winston dependency

### ISSUE THREAD

**Issue by ansarizafar** [notifme/notifme-sdk#41]
I want to replace winston with pino logger http://getpino.io/#/, which is much faster than winston. Can I use my own pino instance with notifme?

**Comment by BDav24** [comment]
Hi @ansarizafar 
It's not possible with the options, but you can override the inner instance:
```js
const notifmeSdk = new NotifmeSdk({})
notifmeSdk.logger.innerLogger = {
  log: (level, info, extra) => { ... }
}
```
(`log` will be called here: https://github.com/notifme/notifme-sdk/blob/master/src/util/logger.js#L27)
I haven't tested but this should work (re-open if it's not the case, we'll work it out).
