### ISSUE TITLE
notificationCatcher: unable to send attachements via email

### ISSUE THREAD

**Issue by vmarchaud** [notifme/notifme-sdk#52]
It seems that the library never `attachements` to the notification catcher : https://github.com/notifme/notifme-sdk/blob/master/src/providers/email/notificationCatcher.js#L8
Is this a expected behavior even if its defined as available in the request : https://github.com/notifme/notifme-sdk/blob/master/src/models/notification-request.js#L17

Regards

**Comment by BDav24** [comment]
You're right, it should be easy to send `attachments` (https://github.com/notifme/catcher/blob/master/scripts/send.js#L30-L32). Would you like to make a pull request?

**Comment by mrfrase3** [comment]
I just noticed that I had patched this years ago, and apparently never made a PR, pretty simple fix.

NB: I've noticed another bug with the catcher where only the latest email attachments will be visible, but it's better than nothing and I think most people want to make sure the files are actually sending through correctly anyway.
