### ISSUE TITLE
Custom email headers

### ISSUE THREAD

**Issue by adambowles** [notifme/notifme-sdk#59]
If I want to supply a custom header, will I have to implement a custom email handler, or does SMTP provider have this functionality?

**Comment by BDav24** [comment]
Hi, have you tried simply passing the header in your request?

```js
notifmeSdk.send({
  email: {
    from: 'me@example.com',
    to: 'john@example.com',
    // ....,
    headers: {
      'x-my-custom-header': 'my-value'
    }
  }
})
```

**Comment by adambowles** [comment]
@BDav24 That doesn't work

**Comment by BDav24** [comment]
Ho you meant in the "notification catcher" provider, then no, custom headers don't appear there. But they should work for real smtp providers.

**Comment by adambowles** [comment]
Ah great, I'll try that thanks
