### ISSUE TITLE
Vote for Botkit integration ( as a bridge to FB, Hangouts, Teams, Websocket, Webhooks etc )

### ISSUE THREAD

**Issue by DhavalW** [notifme/notifme-sdk#67]
Some of the missing channels seem to be supported by [botkit](https://botkit.ai/docs/v4/) (FB Messenger, Hangouts, MS Teams etc). Is an integration doable ? Any tips, pros n cons ?

**Comment by BDav24** [comment]
Well I guess it's doable, but 2 way-communication requires to expose your service, which is not currently the case (this is only a lib).

The main idea here is to standardize the necessary parameters by channels, no matter the provider... so FB, Hangouts, Slack & co might be standardized under the channel "instant messages", I don't really know if that would be useful.
