### ISSUE TITLE
Vote for Sendgrid Email API

### ISSUE THREAD

**Issue by mjsisley** [notifme/notifme-sdk#7]
Hey, this library looks great at first look! Thanks to the authors for getting this together!

I'd like to vote for Sendgrid. 

I need multiple notifications (Twilio + Sendgrid) for an upcoming project and would love to give this library a try. I may take a crack at a PR in the coming weeks if I can squeeze it in.

**Comment by BDav24** [comment]
Hi @mjsisley
Sure, a pull request is always welcome!
