### ISSUE TITLE
node-fetch upgrade to 2.6.1

### ISSUE THREAD

**Issue by 31453** [notifme/notifme-sdk#71]
GitHub has issued a [security advisory for node-fetch](https://github.com/advisories/GHSA-w7rc-rwvf-8q5r). Please upgrade the node version to 2.6.1.

Thanks!

**Comment by 31453** [comment]
Fixed in #76 Thanks!

**Comment by BDav24** [comment]
Available from https://github.com/notifme/notifme-sdk/releases/tag/v1.10.0
