### ISSUE TITLE
Error require in Sailjs 1.x

### ISSUE THREAD

**Issue by hung211097** [notifme/notifme-sdk#73]
Hi, I used this package for notification feature but when I tried to require const NotifmeSdk = require("notifme-sdk").default;
 and called new NotifmeSdk({}), I cannot lift the sailjs app. I got this error {"code":"include-all:COULD_NOT_REQUIRE","raw":{},"filepath":"/home/nguyenhung/Documents/Git/notifier/api/controllers/noti/async.js","level":"error","message":"Failed to lift app:","severity":"error"}.
I think the reason is es6 syntax. How can I resolve this?
Thank you.

**Comment by BDav24** [comment]
Hi, I'm not sure es6 syntax is the problem here. If you can make a minimal repo and describe the steps to reproduce the error I can try to look into it when I have the time.

**Comment by hung211097** [comment]
![image](https://user-images.githubusercontent.com/33419249/96822804-21fdf800-1455-11eb-9f74-f7a766048971.png)
![image](https://user-images.githubusercontent.com/33419249/96822829-33470480-1455-11eb-9515-970b6e94633f.png)
When I use **const NotifmeSdk = require('notifme-sdk').default;**
**Everything will be fine if I don't use it after that**. Whenever I init it through new NotifmeSdk(), I receive error from sailjs

{"code":"include-all:COULD_NOT_REQUIRE","raw":{},"filepath":"/home/nguyenhung/Documents/Git/notifier/api/controllers/noti/async.js","level":"error","message":"Failed to lift app:","severity":"error"}

I think the root is from the "export & import" in the package

**Comment by hung211097** [comment]
I solved the problem when I added the multiProviderStrategy: 'fallback' in custom channels, thank you
