### ISSUE TITLE
Nothing in my browser nor in terminal

### ISSUE THREAD

**Issue by Syedayesha** [notifme/notifme-sdk#9]
As in readme file I made changes to code.When I run the code with `yarn run notifiction catcher` as mentioned in readme file I am getting errors regarding yarn.So that I run the code with yarn run run-catcher then in terminal I am getting this

**

> yarn run v0.27.5
> $ notification-catcher
> NotificationCatcher webapp running at http://0.0.0.0:1080
> NotificationCatcher SMTP Server running at 0.0.0.0:1025

**

When I run the following url in my browser http://localhost:1080 I am getting notifme page but I am not getting a message(as shown in readme file) which I am sending in code.

**Comment by BDav24** [comment]
Hi @Syedayesha, the log for the `notification-catcher` is ok.

> Note: there is a typo in your first command: `yarn run notifiction catcher` => `yarn run notification-catcher`

Can you show me the rest of your code?

**Comment by Syedayesha** [comment]
Sorry for that.And Thanks for your quick reply I clone th code from this github.I placed my nexmo number in `notifme-sdk-master/examples/ simple.js`  file and I did the same thing in` notifme-sdk-master/examples/ with-notification-catcher.js` file.And I used my nexmo api_key and secret_key in 
`notifme-sdk-master/src/models/provider-sms.js`.So please help me to overcome this issue

**Comment by BDav24** [comment]
Have you run the example? (`yarn run babel-node examples/with-notification-catcher.js`)
If yes, what is the log of the command?

> Note: if you're trying to see the sms in the notification catcher, no need to add your Nexmo credentials.

**Comment by Syedayesha** [comment]
I am getting this error.
yarn run v0.27.5
warning package.json: No license field
error Command "with-notification-catcher.js" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this com
and.

**Comment by BDav24** [comment]
Are you running the command in `notifme-sdk` folder?

**Comment by Syedayesha** [comment]
Yes..How can I run this command outside of the notifme-sdk?Help me to get out of this..

**Comment by BDav24** [comment]
Given the error, the only thing I can tell you is to double-check your current folder. You should be in the root folder of the project. (`pwd` displays where you are).
